package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	httpSwagger "github.com/swaggo/http-swagger"

	_ "fintech-monolith/apps/monolith-api/docs" // docs is generated by Swag CLI, you have to import it.

	app "fintech-monolith/domains/payments/application"
	"fintech-monolith/infra/database/notifications"
	"fintech-monolith/infra/database/payments"
	"fintech-monolith/infra/messaging/pix"
	httphandler "fintech-monolith/apps/monolith-api/http"
)

// @title           Fintech Monolith API
// @version         1.0
// @description     API monolítica para gerenciamento de pagamentos PIX e notificações
// @description     Esta é uma implementação monolítica onde todos os domínios compartilham o mesmo banco de dados

// @contact.name   Fintech Dev
// @contact.url    https://github.com/fintechdev

// @host      localhost:8080
// @BasePath  /

// @schemes   http
func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		log.Fatal("DATABASE_URL is required")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Banco de dados compartilhado - todos os domínios usam o mesmo banco
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer pool.Close()

	// Repositórios compartilhando o mesmo banco
	paymentRepo := payments.NewPgPixPaymentRepository(pool)
	notificationRepo := notifications.NewPgNotificationRepository(pool)
	gateway := pix.NewBacenPixGateway()

	// Event broadcaster para observabilidade em tempo real
	eventBroadcaster := httphandler.GetBroadcaster()

	// Use case que usa ambos os repositórios (comunicação direta no monólito)
	createUC := app.NewCreatePixPaymentUseCase(paymentRepo, notificationRepo, gateway, eventBroadcaster)

	facade := httphandler.NewPaymentsFacade(createUC, paymentRepo)

	mux := http.NewServeMux()
	
	// Health check endpoint
	mux.HandleFunc("/health", healthCheck)
	
	// Swagger UI
	mux.HandleFunc("/swagger/", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8080/swagger/doc.json"),
		httpSwagger.DeepLinking(true),
		httpSwagger.DocExpansion("none"),
		httpSwagger.DomID("swagger-ui"),
	))
	
	// API routes
	facade.RegisterRoutes(mux)

	srv := &http.Server{
		Addr:         ":" + port,
		Handler:      mux,
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 10 * time.Second,
	}

	log.Println("Monolith API listening on :" + port)
	log.Println("NOTE: This is a monolithic service with shared database")
	log.Println("Swagger UI available at: http://localhost:" + port + "/swagger/index.html")
	log.Fatal(srv.ListenAndServe())
}

// healthCheck godoc
// @Summary      Health check
// @Description  Verifica se a API está funcionando
// @Tags         health
// @Accept       json
// @Produce      json
// @Success      200  {object}  map[string]string
// @Router       /health [get]
func healthCheck(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(`{"status":"ok","type":"monolith"}`))
}
